services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: 'root'
    ports:
      - 5432:5432
  rest-api:
    build: .
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: sh -c 'yarn && yarn start:dev'
    depends_on:
      - db