services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'ebanxs-take-home-assignment-development'
    ports:
      - 5555:5432
  rest-api:
    build:
      dockerfile: Dockerfile.development
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - db
