### Resets the Database records
POST http://localhost:3000/reset

### Gets the Account (100) current balance
GET localhost:3000/balance?account_id=100

### Gets the Account (300) current balance
GET localhost:3000/balance?account_id=300

### Creates a Deposit Event for Account (100)
POST localhost:3000/event
Content-Type: application/json

{
  "type": "deposit",
  "destination": 100,
  "amount": 151
}

### Creates a Withdraw Event for Account (100)
POST localhost:3000/event
Content-Type: application/json

{
  "type": "withdraw",
  "origin": 100,
  "amount": 1
}

### Creates a Transfer Event for Account (100) to Account (300)
POST localhost:3000/event
Content-Type: application/json

{
  "type": "transfer",
  "origin": 100,
  "destination": 300,
  "amount": 50
}

###



